### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [alexpark07/ARMSCGen#2]
it is nice to see you also use Unicorn here! linked to your tool from our website now: http://www.unicorn-engine.org/showcase/

i think the README should mention that users need to install Unicorn as dependency?

keep it up, cheers!

**Comment by alexpark07** [comment]
Sorry for the late reply and thank you for noticing me.

README.md file has been updated.

**Comment by aquynh** [comment]
i think you can make use of Keystone (www.keystone-engine.org) as well? it is a true framework, so you can avoid those hacks with GAS at https://github.com/alexpark07/ARMSCGen/blob/master/asem/asem.py

Keystone is cross-platform (support Windows natively), so ARMSCGen can run on Windows, too.

**Comment by alexpark07** [comment]
Wow, thank you for introducing the brilliant tool for me. 
In the near future, I'll upgrade my toys.

Thanks,
-Alex
